# Generated by Django 4.2.4 on 2023-08-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOne', '0004_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/productos/'),
        ),
    ]
